# Site settings
title: shane tully
email: shane@shanetully.com
description: "Ramblings of a software engineer"
baseurl: ""
images_dir: "/assets/images/"

# Build settings
markdown: kramdown
permalink: /:year/:month/:title/
excerpt_separator: <!--more-->
paginate: 5
plugins: [jekyll-paginate]
exclude: [Makefile, README.md]