# Site settings
title: ephemeral.cx
name: kira tully
email: "&#x6B;&#x69;&#x72;&#97;&#x40;&#x6B;&#x69;&#x72;&#x61;&#x74;&#117;&#108;&#x6c;&#x79;&#x2E;&#x63;&#111;&#109;"
description: My little corner of the web for sharing wherever my interests take me.
baseurl: ""
images_dir: "/assets/images/"

# Build settings
markdown: kramdown
permalink: /:year/:month/:title/
excerpt_separator: <!--more-->
paginate: 5
paginate_path: /blog/page:num
plugins: [jekyll-paginate]
exclude: [Makefile, README.md]

collections:
  albums:
    order:
      - backpacking.md
      - aviation_idaho.md
      - astrophotography.md
      - skiing.md
      - aviation_washington.md
      - wildlife.md
      - aviation_montana.md
      - aurora_borealis.md
      - mt_baker.md
      - sperry_chalet.md
    output: true
