# Site settings
title: shane tully
email: shane@shanetully.com
description: "Ramblings of a software engineer"
baseurl: ""
images_dir: "/assets/images/"

# Build settings
markdown: kramdown
#permalink: pretty
permalink: /:year/:month/:title
highlighter: pygments
excerpt_separator: <!--more-->
paginate: 5
